// @include scripts/foundation/setup-and-surfaces.js
// @include scripts/foundation/notifications.js
// @include scripts/foundation/api-client.js
// @include scripts/foundation/presentation.js
// @include scripts/foundation/settings-secrets.js
// @include scripts/shared/state.js
// @include scripts/foundation/progress-state.js
// @include scripts/foundation/dialogs.js
// @include scripts/foundation/readiness.js
// @include scripts/features/legacy-discovery-account.js
// @include scripts/features/legacy-dashboard-social.js
// @include scripts/foundation/navigation.js
// @include scripts/features/legacy-content-publishing.js
// @include scripts/features/legacy-settings.js
// @include scripts/features/legacy-actions-controllers.js
// @include scripts/foundation/lifecycle.js
// @include scripts/features/legacy-publish-helpers.js
