// @include scripts/foundation/ui-feedback-state.js
// @include scripts/features/shell/setup-banner.js
// @include scripts/features/shell/sidebar.js
// @include scripts/features/shell/supporting-surfaces.js
// @include scripts/foundation/notifications.js
// @include scripts/foundation/api-client.js
// @include scripts/foundation/presentation.js
// @include scripts/foundation/settings-secrets.js
// @include scripts/shared/state/content-and-runtime.js
// @include scripts/features/shell/update-state.js
// @include scripts/features/shell/log-state.js
// @include scripts/foundation/mobile-state.js
// @include scripts/features/shell/update.js
// @include scripts/shared/state/settings-and-automation.js
// @include scripts/foundation/progress-state.js
// @include scripts/foundation/dialogs.js
// @include scripts/foundation/readiness.js
// @include scripts/features/legacy-discovery-content.js
// @include scripts/features/shell/dashboard-content.js
// @include scripts/features/shell/account-overview.js
// @include scripts/features/shell/account-actions.js
// @include scripts/features/shell/dashboard.js
// @include scripts/features/shell/activity-logs.js
// @include scripts/features/shell/system-logs.js
// @include scripts/features/shell/celebration.js
// @include scripts/features/shell/clock.js
// @include scripts/features/legacy-social.js
// @include scripts/foundation/navigation.js
// @include scripts/features/legacy-content-publishing.js
// @include scripts/features/legacy-settings.js
// @include scripts/features/legacy-actions-controllers.js
// @include scripts/foundation/lifecycle.js
// @include scripts/features/legacy-publish-helpers.js
