// @include scripts/foundation/ui-feedback-state.js
// @include scripts/features/shell/setup-banner.js
// @include scripts/features/shell/sidebar.js
// @include scripts/features/shell/supporting-surfaces.js
// @include scripts/foundation/notifications.js
// @include scripts/foundation/api-client.js
// @include scripts/foundation/presentation.js
// @include scripts/foundation/settings-secrets.js
// @include scripts/features/content/state-core.js
// @include scripts/features/discovery/state.js
// @include scripts/features/settings/state.js
// @include scripts/features/content/table-state.js
// @include scripts/shared/runtime-state.js
// @include scripts/features/shell/update-state.js
// @include scripts/features/shell/log-state.js
// @include scripts/foundation/mobile-state.js
// @include scripts/features/shell/update.js
// @include scripts/features/automation/state.js
// @include scripts/foundation/progress-state.js
// @include scripts/foundation/dialogs.js
// @include scripts/foundation/readiness.js
// @include scripts/features/content/trend-table.js
// @include scripts/features/discovery/trend-collection.js
// @include scripts/features/content/blog-tabs.js
// @include scripts/features/discovery/quick-discovery.js
// @include scripts/features/discovery/trend-posting.js
// @include scripts/features/discovery/naver-comment-draft.js
// @include scripts/features/content/tab-navigation.js
// @include scripts/features/publishing/preview-utils.js
// @include scripts/features/shell/dashboard-content.js
// @include scripts/features/recommendations/center.js
// @include scripts/features/shell/account-overview.js
// @include scripts/features/shell/account-actions.js
// @include scripts/features/shell/dashboard.js
// @include scripts/features/shell/activity-logs.js
// @include scripts/features/shell/system-logs.js
// @include scripts/features/shell/celebration.js
// @include scripts/features/shell/clock.js
// @include scripts/features/social/manual-state.js
// @include scripts/features/social/manual-composer.js
// @include scripts/features/social/manual-optimization.js
// @include scripts/features/social/manual-publish.js
// @include scripts/features/social/manual-lifecycle.js
// @include scripts/features/blog-next/shell.js
// @include scripts/foundation/navigation.js
// @include scripts/features/content/blog-topics.js
// @include scripts/features/content/shopping-items.js
// @include scripts/features/content/blog-batch.js
// @include scripts/features/settings/writing-preferences.js
// @include scripts/features/settings/writing-profile-settings.js
// @include scripts/features/settings/buffer.js
// @include scripts/features/settings/sns-runtime.js
// @include scripts/features/settings/major-form.js
// @include scripts/features/settings/ai-models.js
// @include scripts/features/settings/save-lifecycle.js
// @include scripts/features/settings/shopping-images.js
// @include scripts/features/settings/mcp-token.js
// @include scripts/features/settings/google-sheets.js
// @include scripts/features/settings/google-auth.js
// @include scripts/features/settings/platform-auth.js
// @include scripts/features/automation/blog-collect-ui.js
// @include scripts/features/automation/shared-normalization.js
// @include scripts/features/automation/blog.js
// @include scripts/features/automation/shopping.js
// @include scripts/features/legacy-actions-controllers.js
// @include scripts/foundation/lifecycle.js
// @include scripts/features/publishing/wordpress-controls.js
// @include scripts/features/publishing/shared-preferences.js
// @include scripts/features/publishing/shopping-controls.js
